export default interface ControleDeComissaoSintetico {
    empresaId: number;
    empresaRazaoSocial: string;
    centroDeCustoSigla: string;
    centroDeCustoDescricao: string;
    propostaId: number;
    propostaIdVinculado: string;
    propostaProspectId: number;
    propostaProspectNome: string;
    propostaProspectAreaId: number | undefined;
    propostaProspectAreaDescricao: string | undefined;
    propostaDataDaProposta: Date;
    propostaValor: number;
    propostaIdentificador: string;
    salaDeVendaId: number;
    salaDeVendaDescricao: string;
    cargoId: number;
    cargoNome: string;
    pessoaId: number;
    pessoaNome: string;
    pessoaPossuiPJVinculado: boolean;
    previo: boolean;
    origemId: number;
    origemDescricao: string;
    ordemDeComissao: number;
    parcelamentoOriginal: number;
    parcelamentoAtual: number;
    parcela: number;
    indireto: boolean;
    sobreRecebimento: boolean;
    valorOriginal: number;
    valorAtual: number;
    tipoId: number;
    tipoDescricao: string;
    statusId: number;
    statusDescricao: string;
    faixaInicial: string;
    faixaFinal: string;
    acrescimoMetaBatida: number;
    regraGeral: string;
    statusDoRecebimentoDescricao: string;
    vencimento: Date | undefined;
}