export default interface Informacoes {
    observacao: string,
    torre: string,
    pavimento: string,
    apartamento: string,
    cota: string,
    areaPrivativa: string,
    areaComum: string,
    garagem: string,
    qtdeQuartos: string,
    qtdeSemanas: string,
    vista: string,
    quadra: string,
    lote: string,
    frente: number,
    confrontoFrente: string,
    fundo: number,
    confrontoFundo: string,
    esquerda: number,
    confrontoEsquerdo: string,
    direita: number,
    confrontoDireito: string,
    chanfro: number,
    matricula: string,
    dataMatricula: string,
}